Backhand & Piledrive
ZeDespo/Ultimate-Ganondorf pull request #3
Opened 2024-08-24 16:32 UTC by FatherOfEgg

- `config.json` and romfs
  - `share-to-added` does not work for Ganon
  - Added animations for backhand
- Backhand is a new motion
  - No longer replaces side b animations and acmds
    - Does not affect piledrive acmd anymore, hopefully
- New down b status
  - Transitions to the status used for piledrive if in the air
- Removed unused files and variables
  - Were being used by a previous implementation for piledrive

2024-08-24 17:16 UTC, ZeDespo requested changes
This is some incredibly clean code! There are two documentation requests and one possible file-merge to address, then we can merge the code!

2024-08-24 17:16 UTC, ZeDespo commented on src/ganon/acmd/specials/special_air_side_fall.rs
I am confused regarding when this hitbox would activate. I THINK it's when Ganondorf is falling to the ground from the new down b. Can you specify it as a docstring for the function?

2024-08-24 17:16 UTC, ZeDespo commented on src/ganon/acmd/specials/special_air_side.rs
I understand this is for the original side special, but when do these hitboxes get activated? At the landing for side special, right? Would you be able to add a small docstring for me please?

Also, if `special_air_side_fall` and this file have a lot in common, can we place it in the same file? I'd like to keep to a one file one move convention for acmd.

2024-08-24 17:36 UTC, FatherOfEgg commented on src/ganon/acmd/specials/special_air_side_fall.rs
Yes, you're correct. This hitbox comes out when Ganon is falling. The acmd is a combination from dark_rupture and Ganon's original acmd. However, Ganon does a little hop before falling. That little hop is it's own animation/acmd, so if you want a hitbox or whatever at the very start of it, you have to edit that acmd.

2024-08-24 17:45 UTC, FatherOfEgg commented on src/ganon/acmd/specials/special_air_side.rs
This file/animation/acmd is essentially the landing hitbox. I might've misinterpreted `dark_rupture` and thought that it had a landing hitbox. What would you like to do?

1. Keep both falling and landing hitboxes/files
2. Move the landing hitboxes to his falling hitbox (`special_air_side_fall`)
3. Merge falling and landing files

If you want a combination of the 3, I can move the hitboxes from `special_air_side` into `special_air_side_fall` so that it behaves more like how you had it for `dark_rupture`. Then we can just have `special_air_side` (landing hitboxes) have placeholder acmd's.

2024-08-24 23:55 UTC, ZeDespo commented on src/ganon/acmd/specials/special_air_side_fall.rs
Okay, thanks for the clarification! The hitboxes for this status script are still TBD, just need to keep it in mind.

2024-08-24 23:55 UTC, ZeDespo commented on src/ganon/acmd/specials/special_air_side.rs
If we can do 2 & 3, it would be most optimal!

2024-08-25 01:57 UTC, FatherOfEgg commented on src/ganon/acmd/specials/special_air_side.rs
Just to make sure, do you want me to keep both falling and landing hitboxes (how it currently is)? Or do you want me to make it more like how you originally had it in `dark_rupture`, where you had a strong hitbox followed by a weak hitbox, and no landing hitbox? I can still merge the 2 together, but just not install the landing hitbox.

2024-08-25 17:45 UTC, ZeDespo commented on src/ganon/acmd/specials/special_air_side.rs
Having the original behavior of the move would be great. I want to keep it as close to the original moveset as possible.

2024-08-25 22:56 UTC, FatherOfEgg commented on src/ganon/acmd/specials/special_air_side.rs
If that's the case, should we just not have the landing hitbox at all (`special_air_side`)? The only file/acmd we'll have is just the falling hitbox (`special_air_side_fall`)

2024-08-25 23:46 UTC, ZeDespo commented on src/ganon/acmd/specials/special_air_side.rs
Yeah that makes sense to me. We got the hand hitbox, then the resulting explosion. No need for anything extra

2024-08-27 00:37 UTC, ZeDespo approved these changes
Marvelous work!

2024-08-27 00:44 UTC, merged